site_name: Void Migration

theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown_include.include:
        base_path: json
nav:
  - index.md
  - reference.md