name: Bundle for Linux

on: [push]

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: sudo apt-get install -y libmtdev1 xvfb
      - run: pip install -e .
      - run: xvfb-run -a pyinstaller build.spec

      - uses: actions/upload-artifact@v4
        with:
          name: Linux App
          path: dist/VoidMigration