name: Bundle for Linux

on: [push]

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: apt-get install -y libmtdev1
      - run: pip install -e .
      - name: Create Executable
        uses: martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.11'
          spec: 'build.spec'
          upload_exe_with_name: 'Void Migration'
          options: --onefile, --name "Void Migration", --windowed, -y