name: Bundle for Windows

on: [push]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: python -m pip install --upgrade pip
      - run: pip install -e .
      - run: |
          choco install opengl
          $env:PATH += ";C:\tools\opengl"
      - run: pyinstaller build.spec --distpath dist/windows/${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: Windows App ${{ matrix.arch }}
          path: dist/windows/${{ matrix.arch }}/VoidMigration
