name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      # - uses: actions/setup-node@v2
      # - run: pip install pycco
      # - run: pycco void-migration/*.py
      # - run: touch docs/.nojekyll
      - run: pip install numpy matplotlib tqdm json5
      - run: pip install mkdocs "mkdocstrings[python]" mkdocs-material
      - run: mkdocs gh-deploy --force
      # - run: mkdocs build

      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@v4.2.5
      #   with:
      #     branch: gh-pages
      #     # folder: docs
      #     folder: site
