name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      # - uses: actions/setup-node@v2
      # - run: pip install pycco
      # - run: pycco void-migration/*.py
      # - run: touch docs/.nojekyll
      - run: sudo apt install -y libeigen3-dev
      - run: pip install -e .
      - run: mkdocs gh-deploy --force
      - run: python -m unittest

  post_success:
    runs-on: ubuntu-latest
    steps:
    - name: if_push
      if: ${{ github.event_name == 'push' }}
      run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{
            "text": "New push to repo. Latest commit message: ${{ github.event.head_commit.message }}"
          }' ${{ secrets.WEBHOOK_URL }}
    - name: if_pull_request
      if: ${{ github.event_name == 'pull_request' }}
      run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{
            "text": "New pull request at: ${{ github.event.pull_request.html_url }}"
          }' ${{ secrets.WEBHOOK_URL }}
      
      # - run: mkdocs build

      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@v4.2.5
      #   with:
      #     branch: gh-pages
      #     # folder: docs
      #     folder: site
