name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      # - uses: actions/setup-node@v2
      # - run: pip install pycco
      # - run: pycco void-migration/*.py
      # - run: touch docs/.nojekyll
      - run: pip install -e .
      - run: mkdocs gh-deploy --force

      - run: echo ${{ secrets.WEBHOOK_URL }}

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          data : '{"text": "New push to repo. Latest commit message: ${{ github.event.head_commit.message }}"}'

      # - run: mkdocs build

      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@v4.2.5
      #   with:
      #     branch: gh-pages
      #     # folder: docs
      #     folder: site
